### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/fff#52]
- [ ] Optional tree view.
- [x] `vim`/`nvim` plugin.
- [x] `w3m-img` support.
- [ ] ~~`chafa` support.~~
- [x] Customizable key-binds.
    - #57 
- [ ] Tabs

**Comment by certifiedloud** [comment]
I would love a good vim integration.

**Comment by reavessm** [comment]
maybe [Conque](https://github.com/vim-scripts/Conque-Shell) could help with the vim integration?  like open fff in vim with a conque shell?

**Comment by dylanaraps** [comment]
Vim and Neovim both have builtin terminal emulators now. The only issue is getting `fff` to open files in the already running instance of the editor.
